name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache SBT
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        
    - name: Start Docker Compose
      run: docker compose up -d
      
    - name: Wait for services
      run: |
        timeout 300 bash -c 'until curl -f http://localhost:8080; do sleep 5; done'
        timeout 300 bash -c 'until curl -f http://localhost:8088; do sleep 5; done'
        
    - name: Run tests
      run: sbt test
      
    - name: Run integration tests
      run: ./test_cluster.sh
      
    - name: Stop Docker Compose
      run: docker compose down